### PR TITLE
[ENH] Improve user experience of multi runs GLM reports

### LINKED ISSUE #5449: [BUG]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating system

- [x] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 24.04

### Python version

- [x] 3.13
- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9

### nilearn version

dev

### Expected behavior

have easily browsable multi-run GLM reports

### Current behavior & error messages

This is what I got (from the actual dev doc - not present on main)

https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_two_runs_model.html#contrasts-948876f220be4416ba3aeac1c1d77e22

For multi runs, the UI is bit clunky and does not help a quick evalutation of a run its contrat by how things are listed:

- Design matrices:
  - design matrix - run 1
  - correlation matrix - run 1
  - design matrix - run 2
- Contrasts
  - All contrasts run 1
  - All contrasts run 2 

### Steps and code to reproduce bug

run examples/4_glm_first_level/plot_two_runs_model.py

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #5449

Changes proposed in this pull request:

- improves GLM report with a carousel to navigate run wise information
- carousel is not displayed for single run GLM (or second level GLM)

### CODE REVIEW

File: nilearn/reporting/data/js/carousel.js [hunk 1]
```diff
@@ -1,25 +1,25 @@
 /**
- * A class representing a map carousel that cycles through different maps.
+ * A class representing a carousel that cycles through different objects.
```
Comment (Remi-Gau) [inline nilearn/reporting/data/js/carousel.js:2]: do some renaming of variables as this carousel code works with more than just map images

File: nilearn/reporting/data/html/report_body_template_niftimapsmasker.html [hunk 2]
```diff
@@ -77,10 +77,10 @@ <h4 class="pure-u-1-4 py-3 text-center" style="margin: 0px">
 </div>
 
 <script>
-  {{js_carousel|html}}
-  document.addEventListener("DOMContentLoaded", function () {
-    new MapCarousel("{{unique_id}}", {{displayed_maps}});
-    }
+    { { js_carousel | html } }
```
Comment (Remi-Gau) [inline nilearn/reporting/data/html/report_body_template_niftimapsmasker.html]:
```suggestion
    {{ js_carousel | html }}
```

File: nilearn/reporting/data/html/report_body_template_niftispheresmasker.html [hunk 3]
```diff
@@ -92,10 +92,10 @@ <h4 class="pure-u-1-4 py-3 text-center" style="margin: 0px">
 </div>
 
 <script>
-  {{js_carousel|html}}
-  document.addEventListener("DOMContentLoaded", function () {
-    new MapCarousel("{{unique_id}}", {{displayed_maps}}, true);
-    }
+    { { js_carousel | html } }
```
Comment (Remi-Gau) [inline nilearn/reporting/data/html/report_body_template_niftispheresmasker.html]:
```suggestion
    {{ js_carousel | html }}
```

File: nilearn/reporting/data/html/report_body_template_surfacemapsmasker.html [hunk 4]
```diff
@@ -76,10 +76,10 @@ <h4 class="pure-u-1-4 py-3 text-center" style="margin: 0px">
 </div>
 
 <script>
-  {{js_carousel|html}}
-  document.addEventListener("DOMContentLoaded", function () {
-    new MapCarousel("{{unique_id}}", {{displayed_maps}});
-    }
+    { { js_carousel | html } }
```
Comment (Remi-Gau) [inline nilearn/reporting/data/html/report_body_template_surfacemapsmasker.html]:
```suggestion
    {{ js_carousel | html }}
```

File: nilearn/reporting/data/html/glm_report.html [hunk 5]
```diff
@@ -114,78 +114,111 @@ <h2>Model details</h2>
...
+  <div id="carousel-container-{{unique_id}}">
+
+    {{if n_runs > 1}}
+    <div class="pure-g d-flex justify-content-center align-items-stretch mt-1"
+         id="carousel-navbar">
+      <button class="btn pure-u-1-3 text-center rounded-2 carousel-navbar-element"
+              id="prev-btn-{{unique_id}}">
+        Previous Run
+      </button>
+      <!-- the content of the h4 will be injected by javascript -->
```
Comment (Remi-Gau) [inline nilearn/reporting/data/html/glm_report.html]:
```suggestion
      <!-- the content will be injected by javascript -->
```

File: examples/04_glm_first_level/plot_two_runs_model.py [hunk 6]
```diff
@@ -172,8 +172,8 @@
 # of the resulting brain maps.
 
 # %%
-# Compute the fixed effects statistics
-# using the preprocessed data of both runs.
```
Comment (Remi-Gau) [inline examples/04_glm_first_level/plot_two_runs_model.py:176]: minor change to example to trigger its build

**Comment by Remi-Gau** [comment]
example of the new reports

https://output.circle-artifacts.com/output/job/513a3136-a7f3-460d-8751-0da5fa5b6b0a/artifacts/0/dev/auto_examples/04_glm_first_level/plot_two_runs_model.html#generating-a-report

**Review by hndgzkn — APPROVED** [review]
As far as I can understand, seems ok to me.
