### PR TITLE
[FIX] build examples in PR

### LINKED ISSUE #5016: modified example are not generated in PR
- seems recent: probably due to this https://github.com/nilearn/nilearn/pull/4984

### PR DESCRIPTION
**Pull request by Remi-Gau**
- Closes #5016

### CODE REVIEW

File: build_tools/github/build_type.sh [hunk 1]
```diff
@@ -1,34 +1,92 @@
...
 
+# Checks what doc build type to run.
+# Generate:
+# - 'pattern.txt' that lists the examples to build.
+#   Its content is passed to sphinx_gallery_conf.filename_pattern via a PATTERN env variable.
+# - 'build.txt' that contains the build type to run
+#
+# On the main branch, on tagged released or if requested in the commit message,
+# this exits early and sets things for a full doc build.
+# Otherwise it checks if any examples must be build
```
Comment (bthirion) [inline build_tools/github/build_type.sh:11]:
```suggestion
# Otherwise it checks if any examples must be built
```

File: build_tools/github/build_type.sh [hunk 2]
```diff
@@ -1,34 +1,92 @@
...
+# (either because changed in the PR or requested in the commit message).
```
Comment (bthirion) [inline build_tools/github/build_type.sh:12]:
```suggestion
# (either because it was changed in the PR or requested in the commit message).
```

**Review by bthirion — COMMENTED** [review]
LGTM overall, with minor comments.

**Comment by Remi-Gau** [comment]
thanks for the cross check @bthirion 
will merge as this is blocking some other PR
